### PR TITLE
Migrate to dbt v1.0.3

### PR DESCRIPTION
**Pull request by patped**
Migrate adapter to work with dbt v1.0.3. The work is mostly based on @eredzik fork of the adapter and he should get all the kudos for this work. My only "contribution" is to try getting the changes pulled upstream.

### CODE REVIEW

**Comment by eredzik** [comment]
Thanks @patped for moving this issue forward!
The issue of error_if and warn_if if i remember correctly was fixed by changes in macros/tests/helpers.sql get_test_sql  and test_not_null macro.
I would also suggest using change in rename_relation macro as oracle doesn't allow for direct renaming of views - you have to get definition of the view and recreate it (rename_relation macro).

**Comment by patped** [comment]
Thanks for the info! 💯 I can give you write access to https://github.com/patped/dbt-oracle if you want to do it yourself? 😃

**Comment by patped** [comment]
> I would also suggest using change in rename_relation macro as oracle doesn't allow for direct renaming of views - you have to get definition of the view and recreate it (rename_relation macro).

It works with no issues on our database. I think we run v.19.15. What version are you running on? Anyway, I think this PR should manly focuses on changes to be able to migrate the adapter and issues with renaming should be a separated. Make a new issue and we can discuss it further there.

**Comment by patped** [comment]
> I pushed a work in progress commit where I added the macros/tests/helpers.sql file and it's still not working. 🤔Can you do a review of my code to see what I missed?

I've forgot to include the file in package.

**Comment by patped** [comment]
I've tried to go through the changelogs from v0.20.x up to v.1.0.x and the only thing I want to check more thoroughly is `get_where_subquery` introduced in [v0.21.1](https://github.com/dbt-labs/dbt-core/blob/0.21.latest/CHANGELOG.md#dbt-0211rc2-november-15-2021).

**Comment by mf36** [comment]
Hi guys, I very much appreciate your efforts - kudos  :). 
Do you already know if with the migration changes the snapshot feature will also work properly? It seems to be buggy and not working with the initial adapter.
Cheers!

**Comment by patped** [comment]
I haven't tested or tried to fix the snapshot feature. I have only focused on migrating the existing version of the adapter to 1.0.x and not fixing bugs that's already there.

That said I'm interested in hearing about these kinda bugs so make an issue so we can discuss it further. 😃

**Comment by patped** [comment]
Oracle has now made offisial support for dbt and I see no point to merge this PR

Ref: https://github.com/oracle/dbt-oracle

**Pull request closed without merging**
